# Introducción a Julia - Parte 2

## Funciones

Vamos a ver en este apartado:
* Declaración de una función
* _Duck-typing_ en Julia
* Funciones mutables y no mutables
* Funciones de orden superior

### Declaración de una función
Julia permite declarar de diversas formas una función. La primera requiere de la palabra reservada `function` 

In [18]:
function saludo(name)
    println("Hola $name, uso un argumento")
end

saludo (generic function with 2 methods)

In [19]:
function saludo(name, name2)
    println("Hola $name, uso dos argumentos")
end

saludo (generic function with 2 methods)

In [3]:
function f(x)
    x^2
end

f (generic function with 1 method)

En la declaración anterior no se especificó la palabra reservada `return` para devolver algún valor de la función. Julia devuelve el resultado de la última sentencia de la función. De cualquier modo se puede especificar el valor de regreso haciéndolo explícito.

In [4]:
function g(x)
    
    println("Es el cuadrado de $x")
    return x^2
end

g (generic function with 1 method)

In [5]:
saludo("Oscar") 

Hola Oscar, ¿qué tal estás?


In [6]:
f(5)

25

In [7]:
g(5)

Es el cuadrado de 5


25

Otra forma de declarar funciones es sin la utilización de las palabras reservadas `function` y  `end`.

In [8]:
saludo1(name) = println("Hola $name, qué tal!!")

saludo1 (generic function with 1 method)

In [9]:
f1(x) = x

f1 (generic function with 1 method)

In [10]:
f1(x) = x^2

f1 (generic function with 1 method)

In [11]:

f1(3)

9

In [12]:
f1(5)

25

Este tipo de declaración asemeja más a una sintáxis matemática.

Finalmente, tenemos la siguiente forma de declar una función. El resultado es la declaración de una función **"anónima"**. Este tipo de declaración es similar en concepto al de las funciones lambda.

In [13]:
name -> println("Hola $name, qué tal!!")

#1 (generic function with 1 method)

In [14]:
(name1, name2) -> println("Hola amigos $name1, $name2")

#3 (generic function with 1 method)

Una función declarada de esta forma carece de nombre y solo tiene la especificación del argumento (s) que recibe, separada del cuerpo de la función por `->`. Pareciera que no hay forma de acceder a una función anónima, sin embargo, funciones que "no tienen nombre" son utilizadas en varios casos específicos como se verá más adelante.

Si se desea utilizar una función anónima es posible asignarla a una variable (_binding_). 

In [15]:
saludo2 = (name1, name2) -> println("Hola amigos $name1 y $name2")
saludo2("marco", "javier")

Hola amigos marco y javier


In [16]:
f2 = x -> x^2
f2(5)

25

### Duck-typing en Julia 

_"Si grazna como pato, entonces es un pato"_

Las funciones en Julia siempre funcionarán para entradas para las cuales "encuentre sentido"

In [21]:
saludo(3.14159)

Hola 3.14159, uso un argumento


Las función `saludo()` funciona para un número real

In [22]:
f("hola")

"holahola"

In [23]:
A = rand(3,3)
A

3×3 Matrix{Float64}:
 0.0600279  0.190522  0.66443
 0.794126   0.453897  0.661297
 0.871623   0.635992  0.668798

In [24]:
f(A)

3×3 Matrix{Float64}:
 0.734034  0.520486  0.610245
 0.984523  0.7779    1.27008
 1.14032   0.880088  1.447


La función `f` funciona para enteros, reales o una matriz. También funcionará para una cadena de caracteres pues el operador `^` opera para strings.

In [25]:
f("hi")

"hihi"

Por otra parte, la función f no funcionará con un vector como argumento puesto que `v^2` no es una operación algebráica que esté definida, a diferencia de `A^2` que sí lo es.

In [26]:
v = rand(3)

3-element Vector{Float64}:
 0.01532200052147914
 0.2686677342652717
 0.40194259373361274

In [27]:
f(v)

LoadError: MethodError: no method matching ^(::Vector{Float64}, ::Int64)
Closest candidates are:
  ^(::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:718
  ^(::LinearAlgebra.UniformScaling, ::Number) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/uniformscaling.jl:298
  ^(::LinearAlgebra.Symmetric{var"#s832", S} where {var"#s832"<:Real, S<:(AbstractMatrix{var"#s832"} where var"#s832"<:var"#s832")}, ::Integer) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:868
  ...

### Funciones Mutables vs No Mutables 

Por convención, funciones seguidas de `!` alteran sus contenidos y funciones que no lo tienen no pueden modificarlos.

In [28]:
v = [3, 5, 2]

3-element Vector{Int64}:
 3
 5
 2

In [29]:
sort(v)

3-element Vector{Int64}:
 2
 3
 5

In [30]:
v

3-element Vector{Int64}:
 3
 5
 2

`sort(v)` devuelve un arrego ordenado que contiene los mismos elementos de `v` sin alterar a `v`.

In [31]:
sort!(v)

3-element Vector{Int64}:
 2
 3
 5

In [32]:
v

3-element Vector{Int64}:
 2
 3
 5

`sort!(v)` es altera el argumento `v` que se le pasa a la función.

### Funciones de orden superior 

La función `map()` es una función en Julia que toma como uno de sus argumentos de entrada una _función_. `map()` aplica la función a cada elemento de la estructura de datos que se le pasa.

Por ejemplo, al ejecutar:
```julia
map(f,[1, 2, 3])
```
obtendremos un arreglo de salida donde la función `f()` se aplica a cada uno de los elementos del array `[1, 2, 3]`, es decir,
```julia
[f(1), f(2), f(3)]

In [33]:
map(f,[1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

Se han elevado al cuadrado todos los elementos de `[1, 2, 3]` en lugar de elevar al cuadrado el vector mismo. Para hacer esto, se puede pasar a la función `map()` una función anónima en lugar del nombre de la función:

In [34]:
myfunc = x -> x^3

#9 (generic function with 1 method)

In [35]:
map(myfunc, [1,2,3])

3-element Vector{Int64}:
  1
  8
 27

In [37]:
map(x -> x^3, [1, 2, 3])

3-element Vector{Int64}:
  1
  8
 27

Podemos hacer la operación de **Broadcast** para una función, esto es una "expansión la dimensión unaria" de los objetos que se pasan a la función.

Apliquemos `f()` a una matriz `A` y veamos la diferencia al hacer un _broadcast_ a `f()` sobre `A`

In [38]:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [39]:
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

Esto es:
```julia
f(A) = A^2 = A * A
```

In [40]:
f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

Con el _broadcast_ cada elemento de `A` se elevan al cuadrado

La notación con `.` para hacer el _broadcast_ permite escribir composiciones complejas de expresiones en una manera que parece más natural y cercana a la notación matemática convencional.

In [41]:
A

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

Podemos operar de la siguiente manera:

In [42]:
A .+ 2 .* f.(A) ./ A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

### Operadores como funciones

In [43]:
3 + 4

7

In [44]:
+(3,4)

7

In [45]:
3 // 4

3//4

In [46]:
//(3,4)

3//4

In [47]:
// 

// (generic function with 8 methods)

In [48]:
methods(//)

# 8 methods for generic function "//":
[1] //(n::Integer, d::Integer) in Base at rational.jl:62
[2] //(x::Rational, y::Integer) in Base at rational.jl:64
[3] //(x::Integer, y::Rational) in Base at rational.jl:68
[4] //(x::Complex, y::Real) in Base at rational.jl:78
[5] //(x::Number, y::Complex) in Base at rational.jl:79
[6] //(X::AbstractArray, y::Number) in Base at rational.jl:82
[7] //(x::Rational{BigInt}, y::Rational{BigInt}) in Base.GMP.MPQ at gmp.jl:925
[8] //(x::Rational, y::Rational) in Base at rational.jl:72

Este es el comienzo de lo que se llamaremos **despacho múltiple**. Estamos definiendo una versión o método de esta función la cual acepta argumentos de diferentes tipos, en este caso hay ocho combinaciones diferentes de tipos que podemos usar.

En general, las funciones se implementan especificando la acción que llevará acabo sobre diferentes tipos de datos.

En las **funciones genéricas** no se especifica qué tipo de dato aceptan, al igual que en Python funcionarán siempre que las operaciones realizadas en ellas tengan sentido para el valor de entrada.

In [49]:
duplicate(x) = x^2

duplicate (generic function with 1 method)

In [50]:
duplicate(3)

9

In [51]:
duplicate(3.5)

12.25

In [52]:
 duplicate("hola")

"holahola"

Notemos que la concatenación de cadena utiliza el operador `*`, en lugar del operador `+` como se hace en Python. 

Repetir una cadena entonces es equivalente a aplicar una potencia a un valor entero.

In [53]:
"hello" ^ 2  #duplica

"hellohello"

In [54]:
"hello " * "world" #concatena

"hello world"

In [55]:
"hello " + "world" #error

LoadError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560

El **operador suma no esta definida par las cadenas**. ¿Para cuáles tipos de datos está definida?

In [56]:
+

+ (generic function with 190 methods)

Podemos ver que `+` es tratado como una función y tiene múltiple métodos implementados, los cuales en Julia son considerados como **versiones especializadas** de dicha función para que actúen sobre diferentes tipos de datos:

In [57]:
methods(+)

# 190 methods for generic function "+":
[1] +(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:87
[2] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigInt) in Base.GMP at gmp.jl:528
[3] +(c::Union{Int16, Int32, Int64, Int8}, x::BigInt) in Base.GMP at gmp.jl:534
[4] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigFloat) in Base.MPFR at mpfr.jl:376
[5] +(c::Union{Int16, Int32, Int64, Int8}, x::BigFloat) in Base.MPFR at mpfr.jl:384
[6] +(c::Union{Float16, Float32, Float64}, x::BigFloat) in Base.MPFR at mpfr.jl:392
[7] +(x::Union{Dates.CompoundPeriod, Dates.Period}) in Dates at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/Dates/src/periods.jl:362
[8] +(r1::OrdinalRange, r2::OrdinalRange) in Base at range.jl:1103
[9] +(Da::LinearAlgebra.Diagonal, Db::LinearAlgebra.Diagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:156
[10] +(D::LinearAlgebra.Diagonal, S::LinearAlgebra.Symmetric) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:160
[11] +(D::LinearAlgebra.Diagonal{var"#s832", V} where {var"#s832"<:Real, V<:AbstractVector{var"#s832"}}, H::LinearAlgebra.Hermitian) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:166
[12] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.Bidiagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:125
[13] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.SymTridiagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:135
[14] +(A::LinearAlgebra.Diagonal, B::LinearAlgebra.Tridiagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:163
[15] +(A::LinearAlgebra.Diagonal{var"#s832", V} where {var"#s832"<:Number, V<:AbstractVector{var"#s832"}}, B::LinearAlgebra.UniformScaling) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/special.jl:241
[16] +(x::Rational, y::Integer) in Base at rational.jl:289
[17] +(A::LinearAlgebra.Symmetric, B::LinearAlgebra.Symmetric) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:469
[18] +(S::LinearAlgebra.Symmetric, D::LinearAlgebra.Diagonal) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/LinearAlgebra/src/diagonal.jl:163
[19] +(A::LinearAlgebra.Symmetric{var"#s830", var"#s829"} where {var"#s830", var"#s829"<:(SparseArrays.AbstractSparseMatrix{Tv, Ti} where {Tv, Ti})}, B::SparseArrays.AbstractSparseMatrix{Tv, Ti} where {Tv, Ti}) in SparseArrays at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/SparseArrays/src/linalg.jl:15
[20] +(A::LinearAlgebra.Symmetric, B::SparseArrays.AbstractSparseMatrix{Tv, Ti} where {Tv, Ti}) in SparseArrays at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/SparseArrays/src/linalg.jl:18
[21] +(A::LinearAlgebra.Symmetric{var"#s824", var"#s823"} where {var"#s824"<:Real, var"#s823"<:(SparseArrays.AbstractSparseMatrix{Tv, Ti} where {Tv, Ti})}, B::LinearAlgebra.Hermitian{var"#s822", var"#s821"} where {var"#s822", var"#s821"<:(SparseArrays.AbstractSparseMatrix{Tv, Ti} where {Tv, Ti})}) in SparseArrays at /Applications/Julia-1.6.app/Contents/Resources/julia/share/julia/stdlib/v1.6/SparseArrays/src/linalg.jl:25
[22] +(A::LinearAlgebra.Symmetric{var"#s831", S} where {var"#s831"<:Real, S<:(AbstractMatrix{var"#s832"} where var"#s832"<:var"#s831")}, B::LinearAlgebra.Hermitian) in LinearAlgebra at /Applications/Julia-1.6.app/Contents/Resources/julia/share

Si no deseáramos utilizar el operador `*` para la concatenación de cadenas, podríamos **definir nuestro propio** operador `+` para la concatenación de cadenas: 

In [58]:
import Base.+

In [59]:
string("hola", "crayola")

"holacrayola"

In [60]:
+(s1::String, s2::String) = string(s1,s2)

+ (generic function with 191 methods)

In [61]:
"Hola" + "Crayola"

"HolaCrayola"

A partir de la versión v1.0 es necesario importar explícitamente `Base.x` para extender el método `x`. `Base` es un módulo general en el que se incluyen diversos operadores.

In [62]:
"El valor de x es:" + 3

LoadError: MethodError: no method matching +(::String, ::Int64)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Rational, ::Integer) at rational.jl:289
  ...

In [63]:
3 + "HOLA"

LoadError: MethodError: no method matching +(::Int64, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Union{Int16, Int32, Int64, Int8}, ::BigInt) at gmp.jl:534
  ...

**Ejercio:** Definamos un método del operador `+` para que concatene una caden y un número.

In [64]:
+(s::String, x::Number) = s + "$x"

+ (generic function with 192 methods)

In [65]:
"El valor de x es: " + 3

"El valor de x es: 3"

In [66]:
"El valor de x es: " + 3.5

"El valor de x es: 3.5"

In [67]:
"El valor de x es: " + 3

"El valor de x es: 3"

In [68]:
3 + "Hola" #redefinir +

LoadError: MethodError: no method matching +(::Int64, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:87
  +(::Union{Int16, Int32, Int64, Int8}, ::BigInt) at gmp.jl:534
  ...

In [69]:
"Complex" + (3 + im)

"Complex3 + 1im"

In [71]:
"Cadena" .+ [3,4,5]

3-element Vector{String}:
 "Cadena3"
 "Cadena4"
 "Cadena5"

### Ejercicio

Utiliza el "método de la potencia" para calcular el igenvalor $\lambda_1$ mas grande asociado a la matriz: 
$$ M =\begin{pmatrix}
4 & -5 \\ 
2 & -3
\end{pmatrix}$$

El método consiste en inciar con un vector no cero arbitrario $\mathbf{w}$ y repetidamente multiplicarlo por $M$, con lo que se calcularán potencias de la matriz $M$ multiplicados por $\mathbf{w}$. El resultado converge al eigenvector $\mathbf{v_1}$ correspondiente a $\mathbf{\lambda_1}$

Una forma de resolver el problema es la siguiente:

In [ ]:
using LinearAlgebra

In [ ]:
w = [1., 0]
M = reshape([4., 2, -5,  -3],(2,2))
M, w

In [ ]:
w0 = [1., 0]
w = w0

for i in 1:10
    Mw = M * w
    println("Prod: ", Mw)
    println("maximum: ", maximum(Mw))
    w_new = Mw / maximum(Mw)
    println("w_new: ",  w_new)
    println("error: ", norm(w_new - w))
    w = w_new
    
end

In [ ]:
Mw = M * w

In [ ]:
eigvals(M)

Otra forma de implementación, será por medio del uso de un criterio de paro para el algoritmo:

In [ ]:
w0 = [1., 0]
w = w0
w_new = [1, 1]

tolerance = 1e-10
err = norm(w_new - w)

while err > tolerance
    Mw = M * w
    println("Prod: ", Mw)
    println("maximum: ", maximum(Mw))
    w_new = (Mw)/ maximum(Mw)
    println("w_new: ",  w_new)
    err = norm(w_new - w)
    println("error: ", err)
    w = w_new
end

In [ ]:
Mw = M * w

## Tipos de datos definidos por el usuario

Un tipo de **dato definido por el usuario** ([_composite types_](https://docs.julialang.org/en/v1/manual/types/#Composite-Types)) es una colección de datos. A diferencia de Python, estos tipos no tienen sus propios métodos (funciones internas del tipo).

Los métodos son definidos de forma separada y están caracterizados por _todos_ y cada uno de los tipos de sus argumentos, esto es conocido como **despacho múltiple** (_multiple dispatch_). Nos referiremos a _despacho_ como el proceso de elegir la "versión" adecuada para que ejecute una función.

Un ejemplos sencillo y útil es la definición de un tipo de dato **vector 2D** (vease también el paquete `InmutableArrays.jl`, los arreglos de tamaño fijo han sido incorporados dentro de `Base` de Julia) 

In [ ]:
typeof(3 // 4)

In [ ]:
@which 3//4

In [ ]:
Rational(3)

Vamos a definir el tipo **Vector2D**

In [ ]:
struct Vector2D
    x::Float64
    y::Float64
end

Utilizamos `struct` empaquetar el objeto y almacenarlo de manera eficiente

In [ ]:
methods(Vector2D)

`struct`define por defecto un tipo de [dato inmutable](https://docs.julialang.org/en/v1/base/base/#struct).

Una instancia de este tipo de dato no puede ser modificada después de su construcción. En cambio, usar un `mutable struct` declara un tipo cuyas instancias pueden ser modificadas. Tipos inmutables evitan manipular individualmente los elementos del objeto, tipos mutables permiten manipulaciones.

Los datos almacenados en objetos inmutables están **colocados consecutivamente en memoria** -en lugar de estar en una caja- por lo que no hay punteros al objeto, esto permite mayor velocidad de acceso al objeto; el objeto está almacenado en una forma empaquetada eficiente.

### Definición de operaciones para datos definidos por el usuario

In [ ]:
v = Vector2D(3,4)

In [ ]:
typeof(v)

In [ ]:
v1 = Vector2D(3., 2.)

In [ ]:
v2 = Vector2D(3., 2)

In [ ]:
v3 = Vector2D(3, 2.)

In [ ]:
v4 = Vector2D(1 + 3im, 2 + im)

In [ ]:
typeof(Vector2D)

In [ ]:
fieldnames(Vector2D)

### Ejercicios

- Definir algún otra operacion matemáticas sobre objetos de tipo `Vector2D`.
- Definir una **Partícula** con posición y velocidad en 2D.
- Definir la función `move` que actua sobre la Partícula para moverla cada determinado tiempo $\delta t$.

In [ ]:
v = Vector2D(3,4)
w = Vector2D(5,6)
v + w

In [ ]:
+(v::Vector2D, w::Vector2D) = Vector2D(v.x + w.x, v.y + w.y)

In [ ]:
v + w

In [ ]:
v + w + v

In [ ]:
v * 5

In [ ]:
import Base.*

In [ ]:
methods(*)

In [ ]:
*(v::Vector2D, α::Number) = Vector2D(v.x * α, v.y * α) 

In [ ]:
v * 5

In [ ]:
 v + w * 2 

Ahora deseamos mostrar un objeto de tipo `Vector2D` con un formato particular:

In [ ]:
print(v)

En Python, esto se logra mediante la sobrecarga del método `__repr__`, en Julia tendremos que extender el método `show`:

In [ ]:
show

In [ ]:
import Base.show

In [ ]:
show(io::IO, v::Vector2D) = print(io, "[$(v.x), $(v.y)]")

In [ ]:
v

In [ ]:
print(v)